# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kevin's gSchool blog
url:              http://gs-kl.github.io
paginate:         1
baseurl:          /
author:
  name:           Kevin Litchfield


line_numbers: false

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
